import React from "react";
import { Link } from "react-router-dom";
import "../../styles/global.css";
//import submenu from "../../AdminComponents/Assets/t4s-submenu.css";
import base from "../../AdminComponents/Assets/base.css";
const WOMENLATEST = () => {
 return (


<li id="item_drop_PcAmLN" data-placement="bottom" className="t4s-type__drop t4s-menu-item has--children menu-has__offsets menu-pos__left">
	         <a className="t4s-lh-1 t4s-d-flex t4s-align-items-center t4s-pr" href="/" target="_self">WOMEN</a><div id="content_drop_PcAmLN" className="t4s-sub-menu t4s-pa t4s-op-0 t4s-pe-none" style={{left: '858.144px', top: '100%'}}><div className="t4s-lazy_menu" data-handle="womens-clothing"><link rel="stylesheet" href="//blucheez.fashion/cdn/shop/t/142/assets/t4s-submenu.css?v=177196850476384233671728726942" media="all"><div className="t4s-menu-item"><a href="/collections/womens-wear">View All</a></div><div className="t4s-menu-item has--children">
         <a href="#"><span>Ethnic</span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" width="7" fill="currentColor"><path d="M64 448c-8.188 0-16.38-3.125-22.62-9.375c-12.5-12.5-12.5-32.75 0-45.25L178.8 256L41.38 118.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25l-160 160C80.38 444.9 72.19 448 64 448z"></path></svg></a>
         <ul className="t4s-sub-menu t4s-sub-menu-2 pa op__0"><li className="t4s-menu-item"><a href="/collections/kameez-collection">All Kameez</a></li><li className="t4s-menu-item"><a href="/collections/kurti-collection">One Pcs Kurti </a></li><li className="t4s-menu-item"><a href="/collections/elegant-salwar-kameez">Two Pcs Set</a></li><li className="t4s-menu-item"><a href="/collections/exclusive-salwar-kameez">Three Pcs Set</a></li><li className="t4s-menu-item"><a href="/collections/saree">Saree</a></li><li className="t4s-menu-item"><a href="/collections/blouse">Blouse</a></li></ul>
      </div><div className="t4s-menu-item has--children">
         <a href="#"><span>Western</span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" width="7" fill="currentColor"><path d="M64 448c-8.188 0-16.38-3.125-22.62-9.375c-12.5-12.5-12.5-32.75 0-45.25L178.8 256L41.38 118.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25l-160 160C80.38 444.9 72.19 448 64 448z"></path></svg></a>
         <ul className="t4s-sub-menu t4s-sub-menu-2 pa op__0"><li className="t4s-menu-item"><a href="/collections/western-tops">Western Tops</a></li><li className="t4s-menu-item"><a href="/collections/womens-co-ord-sets">Co-ords</a></li><li className="t4s-menu-item"><a href="/collections/long-dress">Long Dress</a></li><li className="t4s-menu-item"><a href="/collections/womens-tee-shirts">T-Shirts</a></li><li className="t4s-menu-item"><a href="/collections/skirt">Skirt</a></li><li className="t4s-menu-item"><a href="/collections/outerwear">Outerwear</a></li></ul>
      </div><div className="t4s-menu-item"><a href="/collections/ethnic-fusion-wear">Fusion Wear</a></div><div className="t4s-menu-item has--children">
         <a href="/collections/womens-pant"><span>Pants</span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" width="7" fill="currentColor"><path d="M64 448c-8.188 0-16.38-3.125-22.62-9.375c-12.5-12.5-12.5-32.75 0-45.25L178.8 256L41.38 118.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25l-160 160C80.38 444.9 72.19 448 64 448z"></path></svg></a>
         <ul className="t4s-sub-menu t4s-sub-menu-2 pa op__0"><li className="t4s-menu-item"><a href="/collections/womens-pant">View All</a></li><li className="t4s-menu-item"><a href="/collections/women-jeans-pant">Women's Jeans</a></li><li className="t4s-menu-item"><a href="/collections/womens-pajama">Women's Pajama</a></li><li className="t4s-menu-item"><a href="/collections/womens-trouser">Women's Trouser</a></li></ul>
      </div><div className="t4s-menu-item has--children">
         <a href="/collections/womens-winter-wear"><span>Winter Wear</span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" width="7" fill="currentColor"><path d="M64 448c-8.188 0-16.38-3.125-22.62-9.375c-12.5-12.5-12.5-32.75 0-45.25L178.8 256L41.38 118.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25l-160 160C80.38 444.9 72.19 448 64 448z"></path></svg></a>
         <ul className="t4s-sub-menu t4s-sub-menu-2 pa op__0"><li className="t4s-menu-item"><a href="/collections/womens-winter-wear">View All</a></li><li className="t4s-menu-item"><a href="/collections/womens-sweatshirts">Sweatshirts &amp; Sweaters</a></li><li className="t4s-menu-item"><a href="/collections/womens-jackets">Women's Jackets</a></li></ul>
      </div><div className="t4s-menu-item has--children">
         <a href="/collections/jewellery"><span>Jewellery</span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" width="7" fill="currentColor"><path d="M64 448c-8.188 0-16.38-3.125-22.62-9.375c-12.5-12.5-12.5-32.75 0-45.25L178.8 256L41.38 118.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25l-160 160C80.38 444.9 72.19 448 64 448z"></path></svg></a>
         <ul className="t4s-sub-menu t4s-sub-menu-2 pa op__0"><li className="t4s-menu-item"><a href="/collections/earrings">Earrings</a></li></ul>
      </div></div></div></li>

       );
};

export default WOMENLATEST;